/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubespbo;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author BANY A7X
 */
public class login extends javax.swing.JFrame {
    int mouseX;
    int mouseY;
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setOpacity(0.9f); //untuk menjadikan transparan
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoclose = new javax.swing.JLabel();
        logominimize = new javax.swing.JLabel();
        label_judultubes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputusername = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        tombol_signin = new javax.swing.JPanel();
        labeltxtsignin = new javax.swing.JLabel();
        panelcancel = new javax.swing.JPanel();
        label_cancel = new javax.swing.JLabel();
        jLabel2backgorund = new javax.swing.JLabel();
        kepalaform = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        logoclose.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logoclose.setForeground(new java.awt.Color(255, 255, 255));
        logoclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoclose.setText("X");
        logoclose.setFocusable(false);
        logoclose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logocloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logocloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logocloseMouseExited(evt);
            }
        });
        jPanel1.add(logoclose);
        logoclose.setBounds(340, 5, 15, 20);

        logominimize.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        logominimize.setForeground(new java.awt.Color(255, 255, 255));
        logominimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logominimize.setText("-");
        logominimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logominimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logominimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logominimizeMouseExited(evt);
            }
        });
        jPanel1.add(logominimize);
        logominimize.setBounds(310, 4, 20, 20);

        label_judultubes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        label_judultubes.setForeground(new java.awt.Color(255, 255, 255));
        label_judultubes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_judultubes.setText("Layanan Informasi Pengaduan Kerusakan Fasilitas ");
        label_judultubes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                label_judultubesMouseDragged(evt);
            }
        });
        label_judultubes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_judultubesMousePressed(evt);
            }
        });
        jPanel1.add(label_judultubes);
        label_judultubes.setBounds(-1, 0, 360, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username   :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 180, 100, 23);

        inputusername.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.disabledBackground"));
        inputusername.setBorder(null);
        inputusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputusernameActionPerformed(evt);
            }
        });
        jPanel1.add(inputusername);
        inputusername.setBounds(160, 180, 130, 20);

        label_password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label_password.setForeground(new java.awt.Color(255, 255, 255));
        label_password.setText("Password    : ");
        jPanel1.add(label_password);
        label_password.setBounds(50, 230, 110, 16);
        jPanel1.add(inputPassword);
        inputPassword.setBounds(160, 220, 130, 22);

        tombol_signin.setToolTipText("");
        tombol_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombol_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_signinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombol_signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombol_signinMouseExited(evt);
            }
        });

        labeltxtsignin.setText("Sign In");
        tombol_signin.add(labeltxtsignin);

        jPanel1.add(tombol_signin);
        tombol_signin.setBounds(230, 300, 60, 30);

        panelcancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelcancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelcancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelcancelMouseExited(evt);
            }
        });

        label_cancel.setText("Cancel");
        panelcancel.add(label_cancel);

        jPanel1.add(panelcancel);
        panelcancel.setBounds(140, 300, 60, 30);

        jLabel2backgorund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubespbo/images/rsz_20160716_142457_2_-_copy.jpg"))); // NOI18N
        jPanel1.add(jLabel2backgorund);
        jLabel2backgorund.setBounds(0, 30, 360, 480);

        kepalaform.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(kepalaform);
        kepalaform.setBounds(0, 0, 360, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 510);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 360, 30);

        setSize(new java.awt.Dimension(360, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logocloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logocloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_logocloseMouseClicked

    private void logominimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logominimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
        logominimize.setForeground(new Color (242, 241, 239));
        logominimize.setBackground(Color.WHITE);
    }//GEN-LAST:event_logominimizeMouseClicked

    private void label_judultubesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_judultubesMouseDragged
        // TODO add your handling code here: untuk dapat mendrag form login
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setOpacity(0.9f);
        this.setLocation(kordinatX-mouseX, kordinatY-mouseY); //dapat mengklik drag dimanaput posisi kursornya
    }//GEN-LAST:event_label_judultubesMouseDragged

    private void label_judultubesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_judultubesMousePressed
        // TODO add your handling code here:
        mouseX= evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_label_judultubesMousePressed

    private void inputusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputusernameActionPerformed
    
    /*DARI PANELCANCELMOUSECLICKED SAMPAI PANEL tombol_signinMouseExited
      ADALAH UNTUK MERUBAH EXIT DAN WARNA JIKA DI KLIK
    */
    private void panelcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcancelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_panelcancelMouseClicked
//untuk panel tombol cancel
    private void panelcancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcancelMouseEntered
        panelcancel.setForeground(Color.WHITE);
        panelcancel.setBackground(new Color (77, 175, 124));
    }//GEN-LAST:event_panelcancelMouseEntered
//untuk panel tombol cancel
    private void panelcancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcancelMouseExited
        // TODO add your handling code here:
        panelcancel.setForeground(new Color (77, 175, 124));
        panelcancel.setBackground(Color.WHITE);
    }//GEN-LAST:event_panelcancelMouseExited

//untuk panel tombol Sign In
    private void tombol_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_signinMouseClicked
        // TODO add your handling code here:
        String user = inputusername.getText().trim();
        String pass = inputPassword.getText();
        if(user.equalsIgnoreCase("Admin") && pass.equals("123456")){
            new dashboard().setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Incorrect User Name or Password", "warning", 0);
            
        }
        
    }//GEN-LAST:event_tombol_signinMouseClicked
//untuk panel tombol Sign In
    private void tombol_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_signinMouseEntered
        // TODO add your handling code here:
        tombol_signin.setForeground(Color.WHITE);
        tombol_signin.setBackground(new Color (77, 175, 124));
    }//GEN-LAST:event_tombol_signinMouseEntered
//untuk panel tombol Sign In
    private void tombol_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_signinMouseExited
        // TODO add your handling code here:
        tombol_signin.setForeground(new Color (77, 175, 124));
        tombol_signin.setBackground(Color.WHITE);
    }//GEN-LAST:event_tombol_signinMouseExited

//untuk logo close atau exit
    private void logocloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logocloseMouseEntered
        // TODO add your handling code here:
        logoclose.setForeground(Color.RED); //Ketika cursor diarahkan ke logo, maka warna berubah menjadi warna merah
        
    }//GEN-LAST:event_logocloseMouseEntered
//untuk logo close atau exit
    private void logocloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logocloseMouseExited
        // TODO add your handling code here:
        logoclose.setForeground(Color.WHITE); //ketika cursor tidak jadi memilih logo tsbt, maka logo berubah menjadi warna putih
        
    }//GEN-LAST:event_logocloseMouseExited


//untuk logo minisize
    private void logominimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logominimizeMouseEntered
        // TODO add your handling code here:
        logominimize.setForeground(Color.RED);
    }//GEN-LAST:event_logominimizeMouseEntered
//untuk logo minisize
    private void logominimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logominimizeMouseExited
        // TODO add your handling code here:
        logominimize.setForeground(Color.WHITE);
    }//GEN-LAST:event_logominimizeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputusername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2backgorund;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel kepalaform;
    private javax.swing.JLabel label_cancel;
    private javax.swing.JLabel label_judultubes;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel labeltxtsignin;
    private javax.swing.JLabel logoclose;
    private javax.swing.JLabel logominimize;
    private javax.swing.JPanel panelcancel;
    private javax.swing.JPanel tombol_signin;
    // End of variables declaration//GEN-END:variables
}
