/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubespbo;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author BANY A7X
 */
public class mail extends javax.swing.JFrame {
    int mouseX;
    int mouseY;

    /**
     * Creates new form mail
     */
    public mail() {
        initComponents();
        this.setLocationRelativeTo(null); //untuk mengatur posisi ditengah saat kemunculan aplikasi dibuka.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_subjek = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_pesan = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        logominimize = new javax.swing.JLabel();
        logoclose = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_subjek.setText("Layanan Informasi Kerusakan Fasilitas Kampus ITERA");
        jPanel1.add(txt_subjek, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 320, -1));
        jPanel1.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 320, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pesan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Subjek");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, -1));

        txt_pesan.setText("Barang yang anda laporkan telah selesai.");
        txt_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesanActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 420, 110));

        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel1.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        logominimize.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        logominimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logominimize.setText("-");
        logominimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logominimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logominimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logominimizeMouseExited(evt);
            }
        });
        jPanel1.add(logominimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 30));

        logoclose.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logoclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoclose.setText("X");
        logoclose.setFocusable(false);
        logoclose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logocloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logocloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logocloseMouseExited(evt);
            }
        });
        jPanel1.add(logoclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubespbo/images/mail.jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        try{
            if(txt_mail.getText() !=null && !txt_mail.getText().equals("")){
                email Email = new email();
                Email.sendMail(txt_mail.getText(), txt_subjek.getText(), txt_pesan.getText());
                JOptionPane.showMessageDialog(null, "Email berhasil terkirim!");
                
            }else{
                JOptionPane.showMessageDialog(null,"Value required : Mail", "Error", JOptionPane.OK_OPTION);
            }
        }catch(Exception error){
            
        }
    }//GEN-LAST:event_sendActionPerformed

    private void logominimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logominimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
        logominimize.setForeground(new Color (242, 241, 239));
        logominimize.setBackground(Color.BLACK);
    }//GEN-LAST:event_logominimizeMouseClicked

    private void logominimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logominimizeMouseEntered
        // TODO add your handling code here:
        logominimize.setForeground(Color.RED);
    }//GEN-LAST:event_logominimizeMouseEntered

    private void logominimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logominimizeMouseExited
        // TODO add your handling code here:
        logominimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_logominimizeMouseExited

    private void logocloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logocloseMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_logocloseMouseClicked

    private void logocloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logocloseMouseEntered
        // TODO add your handling code here:
        logoclose.setForeground(Color.RED); //Ketika cursor diarahkan ke logo, maka warna berubah menjadi warna merah

    }//GEN-LAST:event_logocloseMouseEntered

    private void logocloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logocloseMouseExited
        // TODO add your handling code here:
        logoclose.setForeground(Color.BLACK); //ketika cursor tidak jadi memilih logo tsbt, maka logo berubah menjadi warna putih

    }//GEN-LAST:event_logocloseMouseExited

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setOpacity(0.9f);
        this.setLocation(kordinatX-mouseX, kordinatY-mouseY); //dapat mengklik drag dimanaput posisi kursornya
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        mouseX= evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void txt_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesanActionPerformed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        this.setOpacity(1.0f);
    }//GEN-LAST:event_jLabel4MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoclose;
    private javax.swing.JLabel logominimize;
    private javax.swing.JButton send;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_pesan;
    private javax.swing.JTextField txt_subjek;
    // End of variables declaration//GEN-END:variables
}
